---
version: "3"

services:
  web:
    build: https://github.com/Priori-Services/Web.git
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - frontend
    environment:
      - "PRIORI_API_ENDPOINT=http://162.20.0.7:80"
    volumes:
      - ${PWD}/container/setup.sql:/usr/config/setup.sql:Z
  api:
    build: https://github.com/Priori-Services/API.git
    hostname: priori_api
    ports:
      - 5000:5000
      - 8080:80
    depends_on:
      - database
    networks:
      frontend:
        ipv4_address: 162.20.0.7
      backend:
        ipv4_address: 172.20.0.7
  database:
    build: https://github.com/Priori-Services/Database.git
    ports:
      - 1433:1433
    hostname: priori_db
    environment:
      - "MSSQL_SA_PASSWORD=${PRIORI_DATABASE_PASSWORD}"
    volumes:
      - ${PWD}/container/setup.sql:/usr/config/setup.sql:Z
    networks:
      backend:
        ipv4_address: 172.20.0.8

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: "162.20.0.0/28"
          gateway: "162.20.0.1"
  backend:
    ipam:
      config:
        - subnet: "172.20.0.0/28"
          gateway: "172.20.0.1"
